import '@/styles/globals.css';

export const metadata = {
  title: 'Frontend Mentor | Body Mass Index Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='h-screen' lang="en">
    <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png" />
      </head>
      <body className='min-h-screen'>
        <div className='flex flex-col min-h-screen items-center bg-pure-white'>
          {children}
        </div>
      </body>
    </html>
  )
}
